[package]
name = "sqlpage"
version = "0.6.12"
edition = "2021"
description = "A SQL-only web application framework. Takes .sql files and formats the query result using pre-made configurable professional-looking components."
keywords = ["web", "sql", "framework"]
license = "MIT"
homepage = "https://sql.ophir.dev/"
repository = "https://github.com/lovasoa/SQLpage"
documentation = "https://docs.rs/sqlpage"

[profile.superoptimized]
inherits = "release"
strip = "debuginfo"
lto = "fat"
panic = "abort"
codegen-units = 2

[dependencies]
sqlx = { version = "0.6", features = ["any", "runtime-actix-rustls", "sqlite", "postgres", "mysql", "chrono"] }
chrono = "0.4.23"
actix-web = { version = "4", features = ["rustls"] }
percent-encoding = "2.2.0"
handlebars = "5.0.0-beta.0"
log = "0.4.17"
env_logger = "0.10.0"
mime_guess = "2.0.4"
futures-util = "0.3.21"
dashmap = "5.4.0"
tokio = { version = "1.24.1", features = ["macros", "rt"] }
tokio-stream = "0.1.9"
anyhow = "1"
serde = "1"
serde_json = { version = "1.0.82", features = ["preserve_order"] }
lambda-web = { version = "0.2.1", features = ["actix4"], optional = true }
sqlparser = { version = "0.34.0", features = ["visitor"] }
async-stream = "0.3"
async-trait = "0.1.61"
async-recursion = "1.0.0"
include_dir = "0.7.2"
config = { version = "0.13.3", features = ["json"] }
markdown = { version = "1.0.0-alpha.9", features = ["log"] }

[build-dependencies]
ureq = "2.6.2"
