name: "deploy website"

on:
  push:
    branches:
      - main

concurrency: site-deploy

jobs:
  deploy_official_site:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: get_gitsha
        name: Make a commit for the official site
        run: |
          cp -r examples/official-site /tmp/
          rm -rf * .[!.]*
          cp -r /tmp/official-site/* .
          git init .
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -am "site update $(date)"
          echo "gitsha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "dokku@${{ secrets.DEPLOY_IP }}:sqlpage"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_host_key: ${{ secrets.SSH_HOST_KEY }}
          git_push_flags: "--force"
          branch: "main"
          ci_commit: ${{ steps.get_gitsha.outputs.gitsha }}
